### ISSUE TITLE
Update Mythril CLI

### ISSUE THREAD

**Issue by informartin** [informartin/VeriSmart#17]
As Mythril has updated its CLI, the respective command has to be updated to be aligned with the new format. Currently, dependencies are not found using the new Mythril version.

**Comment by thecodingshrimp** [comment]
Mythrils CLI was changed quite a bit. At this moment, we can no longer use mythril to check for references to other contracts in the bytecode.

@informartin suggested to use the npm package [evm](https://github.com/MrLuit/evm) to extract references. This would eliminate the need to extract the output from an external cli.

I will investigate if evm is the right package.
