### ISSUE TITLE
Permit continuing interrupted migration

### ISSUE THREAD

**Issue by informartin** [informartin/VeriSmart#19]
Currently, there is no way to continue a migration process after e.g. a transaction failed. We should add an option to continue from a point where it failed before. For instance, we could return the last successfully stored key. That key could then be passed to continue from that point in the key/value mapping. Assuming the key/value map is always in the same order, that should be fine.

**Comment by thecodingshrimp** [comment]
> Assuming the key/value map is always in the same order

Unfortunately, we can't assume the object to always be in the same order ([discussion](https://stackoverflow.com/questions/5525795/does-javascript-guarantee-object-property-order/38218582#38218582)). 

The way I see it there are two options:

- The [map object](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Map) would give us the same order every time, but this could possibly mean a greater code refactoring.
- Save a whole list of keys that were successfully migrated. When continuing the migration, the CLI can just filter out the keys that were migrated already.

**Comment by informartin** [comment]
Alright, the second option sounds alright to me as well.

**Comment by thecodingshrimp** [comment]
The flag I'll implement is `-i/--continue-migration <file.json>`, `interrupted-migration.json` is the default json output file. Continuing the migration is enabled by default and the flag can only change the input/output file.

If the input file was created for another migration process, the started migration process will fail.

The json file will feature a list of objects. One object represents a migrated contract with and the successfully migrated values.
Example:
`
{
    migratedContracts: [
        {
            sourceAddress: String,
            targetAddress: String,
            migrationCompleted: bool,
            migratedKeys: Array 
        }
    ]
}
`
