### ISSUE TITLE
Empty output json file when using cmd get-state with --output parameter

### ISSUE THREAD

**Issue by thecodingshrimp** [informartin/VeriSmart#22]
The flag `--output` is not working and needs to be debugged.

**Comment by thecodingshrimp** [comment]
While working on this issue I noticed that get-state is pretty "basic".

It retrieves the state of a contract without searching for smart contract references in the static code and without pulling the state and static references of referenced contracts.

But this functionality might be necessary to fix issue #18.
Requirements say:
> Add flag `-f --state-file` that takes the key/value mapping stored in the json and **migrates without accessing the source ledger**

Otherwise referenced contracts would still need to be retrieved from the source ledger, hence we would need to access it.

@informartin is #18 solely meant for the state of a contract without including the necessary references to also migrate referenced contracts?

**Comment by informartin** [comment]
Good find! From my point of view, get-state should also store respective dependencies, so that no access to the source ledger is required when migrating using the generated json.
